"""Write THIRD_PARTY_NOTICES.md: every runtime dependency in uv.lock with its version, licence and home page.

  uv run python scripts/third_party_notices.py

The package list comes from uv.lock (the dependencies of ai-pc, followed transitively, without the dev group); the
licence and home page come from each installed package's metadata, so run it in the project's environment.
"""

import importlib.metadata as md
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def runtime_packages():
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    by_name = {p["name"]: p for p in lock["package"]}
    todo = [d["name"] for d in by_name["ai-pc"].get("dependencies", [])]
    seen = set()
    while todo:
        name = todo.pop()
        if name in seen or name not in by_name:
            continue
        seen.add(name)
        todo += [d["name"] for d in by_name[name].get("dependencies", [])]
    return sorted((by_name[n] for n in seen), key=lambda p: p["name"])


def licence(name, meta):
    expr = meta.get("License-Expression")
    if expr:
        return expr
    classifiers = [c.split(" :: ")[-1] for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return ", ".join(dict.fromkeys(classifiers))
    text = (meta.get("License") or "").strip()
    if text and len(text) <= 60 and "\n" not in text:
        return text
    for f in meta.get_all("License-File") or []:  # only a licence file: name it from its first lines
        body = md.distribution(name).read_text(f"licenses/{f}") or md.distribution(name).read_text(f) or ""
        head = " ".join(body.split()[:12])
        if "Apache License" in head and "2.0" in head:
            return "Apache-2.0"
        if head.startswith("MIT License") or "Permission is hereby granted, free of charge" in body[:600]:
            return "MIT"
    return "not stated by the package"


def home(meta):
    urls = [u.split(",", 1)[1].strip() for u in meta.get_all("Project-URL") or [] if "," in u]
    preferred = [u.split(",", 1)[1].strip() for u in meta.get_all("Project-URL") or [] if re.match(r"(?i)(source|repository|homepage|home)\b", u)]
    return meta.get("Home-page") or (preferred or urls or [""])[0]


def main():
    rows = []
    for p in runtime_packages():
        try:
            meta = md.metadata(p["name"])
            lic, url = licence(p["name"], meta), home(meta)
        except md.PackageNotFoundError:
            lic, url = "not installed here", ""
        source = p.get("source", {})
        if "git" in source:
            url = url or source["git"].split("?")[0].split("#")[0]
        rows.append(f"| {p['name']} | {p.get('version', '')} | {lic} | {url} |")
    text = f"""# Third-party notices

AI PC uses the open-source packages below at run time. Each is used under its own licence; the licence texts are in
the packages themselves (in each installed package's `.dist-info` folder) and on their home pages. This file is
generated by `scripts/third_party_notices.py` from `uv.lock`.

## Python packages

| Package | Version | Licence | Home page |
|---|---|---|---|
{chr(10).join(rows)}

## Programs and models used but not included

The desktop programs AI PC drives (for example JianYing, CapCut, Microsoft Office, Blender, GIMP, LibreOffice) and the
local models it uses are installed separately on each PC, from their publishers, under their own licences. They are
not part of this repository. Note in particular:

- The Vocaela click model weights are licensed for non-commercial use only. The TinyClick model (MIT) is the
  alternative for the desktop agent's vision lane.
- Whisper (speech recognition, via faster-whisper) and the YuNet face detector are used under their own licences.

## Logos in the documentation

The program and model logos in `docs/assets/` belong to their owners and appear only to name the programs AI PC works
with. Most are the programs' own icons, read from their installed program files. The rest come from
`@lobehub/icons-static-svg` 1.95.1 (MIT), `@iconify-json/logos` 1.2.15 (CC0-1.0) and `simple-icons` 16.34.0
(CC0-1.0), from the logos shipped with GNU Octave and Rust, and from the HandBrake project's GitHub picture.
`docs/assets/logos/SOURCES.md` gives the source of each file.
"""
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text(text, encoding="utf-8", newline="\n")
    print(f"THIRD_PARTY_NOTICES.md: {len(rows)} packages")


if __name__ == "__main__":
    main()
